services:

  app:
    image: pescel/321_project:1.0.0
    depends_on:
      - mariadb
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mariadb
      - DB_USER=mychat
      - DB_PASSWORD=mychatpassword
      - DB_NAME=mychat
      - SECRET_KEY=${SECRET_KEY}
      - AES_SECRET=${AES_SECRET}

  mariadb:
    image: mariadb:lts-ubi
    volumes:
      - m321_project_mariadb:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret123
      - MYSQL_DATABASE=mychat
      - MYSQL_USER=mychat
      - MYSQL_PASSWORD=mychatpassword
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mariadb
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=supersecret123
    ports:
      - 9200:80

volumes:
  m321_project_mariadb:
